-- Gen1Recomp Vita probe.
--
-- Answers "can this LÖVE runtime run the game, and how fast" without the
-- game itself: Lua flavour, the libraries the engine requires, graphics
-- limits, every real shader the engine ships (shaders.lua, generated by
-- build_vpk.py), threads, the music QueueableSource, and CPU/GPU timings
-- comparable to a desktop run of this same file.
--
-- Results are drawn on screen and written to ux0:data/gen1recomp-probe.txt
-- (plus probe.txt in the LÖVE save directory).  START quits.

-- desktop stand-in for a Vita without a working JIT: PROBE_JIT_OFF=1
if os.getenv("PROBE_JIT_OFF") and jit then jit.off() end

local results = {}
local function add(key, value)
  results[#results + 1] = key .. ": " .. tostring(value)
end
local function section(name)
  results[#results + 1] = "== " .. name
end
local function try(label, fn)
  local ok, value = pcall(fn)
  add(label, ok and value or ("ERROR " .. tostring(value)))
end

local now = love.timer.getTime
local bit = select(2, pcall(require, "bit"))
if type(bit) ~= "table" then bit = nil end

local phase = "static"
local phaseStart = 0
local font, smallFont
local thread, threadChannel, threadStart
local drawStats = { frames = 0, dtSum = 0, worst = 0, cpuSum = 0 }
local tileset, quads, batch, canvas, palShader
local inputLog = {}
local written = false
local writeTarget = "(not written yet)"

-- ---------------------------------------------------------------------------
-- Static facts
-- ---------------------------------------------------------------------------

local function staticInfo()
  section("Lua")
  add("_VERSION", _VERSION)
  add("jit", type(jit) == "table" and jit.version or "absent")
  if type(jit) == "table" then
    add("jit.arch", jit.arch)
    add("jit.os", jit.os)
    local st = { jit.status() }
    add("jit.status", tostring(st[1]))
    add("jit flags", table.concat(st, " ", 2))
  end
  add("require bit", bit and "ok" or "MISSING")
  try("require ffi", function() require("ffi"); return "ok" end)
  add("loadstring", type(loadstring))
  add("setfenv", type(setfenv))
  add("goto syntax", (loadstring or load)("goto x ::x:: return 1") and "ok" or "no")

  section("LOVE")
  add("version", table.concat({ love.getVersion() }, ".", 1, 3))
  add("getOS", love.system.getOS())
  add("cores", love.system.getProcessorCount())
  try("renderer", function()
    local name, version, vendor, device = love.graphics.getRendererInfo()
    return ("%s | %s | %s | %s"):format(name, version, vendor, device)
  end)
  try("texturesize", function() return love.graphics.getSystemLimits().texturesize end)
  try("glsl3", function() return love.graphics.getSupported().glsl3 end)
  try("npot", function() return love.graphics.getSupported().fullnpot end)
  try("canvas rgba8", function() return love.graphics.getCanvasFormats().rgba8 end)
  try("canvas r8", function() return love.graphics.getCanvasFormats().r8 end)
  add("dimensions", table.concat({ love.graphics.getDimensions() }, "x"))
  add("save dir", love.filesystem.getSaveDirectory())
  add("source", love.filesystem.getSource())
  try("working dir", function() return love.filesystem.getWorkingDirectory() end)
  add("joysticks", love.joystick.getJoystickCount())
  try("pad name", function()
    local js = love.joystick.getJoysticks()[1]
    return js and (js:getName() .. " gamepad=" .. tostring(js:isGamepad())) or "none"
  end)
end

-- ---------------------------------------------------------------------------
-- Shaders: every source the engine ships, compiled for real
-- ---------------------------------------------------------------------------

local function shaderInfo()
  section("Shaders (engine sources)")
  local ok, list = pcall(require, "shaders")
  if not ok then add("shaders.lua", "ERROR " .. tostring(list)); return end
  local pass = 0
  for _, entry in ipairs(list) do
    local t0 = now()
    local okNew, shaderOrErr = pcall(love.graphics.newShader, entry.code)
    local ms = (now() - t0) * 1000
    if okNew then
      pass = pass + 1
      add(entry.name, ("ok %.0fms"):format(ms))
    else
      local msg = tostring(shaderOrErr):gsub("%s+", " "):sub(1, 90)
      add(entry.name, "FAIL " .. msg)
    end
  end
  add("shaders compiled", pass .. "/" .. #list)
end

-- ---------------------------------------------------------------------------
-- Bytecode + GC: can this runtime load precompiled chunks safely?
--
-- Shipping the engine as LuaJIT 2.0 bytecode would skip seconds of parsing
-- at startup, but loading bytecode while the collector runs crashes LuaJIT
-- on the desktop (both 2.0 and 2.1: an upstream bug). If this section
-- finishes on the Vita, the game build can ship precompiled; if the probe
-- dies here, the results file stops at this line and that is the answer.
-- ---------------------------------------------------------------------------

local function bytecodeInfo()
  section("Bytecode (engine chunks) + GC")
  local files = love.filesystem.getDirectoryItems("bc")
  if #files == 0 then add("chunks", "none packaged"); return end
  local loader = loadstring or load
  local loaded, failed = 0, 0
  local t0 = now()
  for round = 1, 5 do
    for _, name in ipairs(files) do
      local data = love.filesystem.read("bc/" .. name)
      local chunk = data and loader(data, "@" .. name)
      if chunk then loaded = loaded + 1 else failed = failed + 1 end
      collectgarbage("step")      -- the combination that crashes on desktop
    end
  end
  collectgarbage("collect")
  add("chunks", ("%d files x5 rounds: %d loaded, %d failed, %.0f ms"):format(
    #files, loaded, failed, (now() - t0) * 1000))
  add("survived GC", "yes")
end

-- ---------------------------------------------------------------------------
-- Thread: the chip worker needs love.thread plus bit inside the thread
-- ---------------------------------------------------------------------------

local THREAD_CODE = [[
local ch = ...
local okBit = pcall(require, "bit")
local okSound = pcall(require, "love.sound")
local okData = okSound and pcall(love.sound.newSoundData, 8192, 44100, 16, 2)
ch:push(("bit=%s love.sound=%s SoundData=%s"):format(tostring(okBit), tostring(okSound), tostring(okData)))
]]

local function startThread()
  local ok, err = pcall(function()
    threadChannel = love.thread.newChannel()
    thread = love.thread.newThread(THREAD_CODE)
    thread:start(threadChannel)
    threadStart = now()
  end)
  if not ok then add("thread", "ERROR " .. tostring(err)) end
end

-- ---------------------------------------------------------------------------
-- CPU: synth-shaped loop, table churn, string formatting
-- ---------------------------------------------------------------------------

local function benchSynth(n)
  if not bit then return nil end
  local band, bor, bxor, rshift, lshift = bit.band, bit.bor, bit.bxor, bit.rshift, bit.lshift
  local floor = math.floor
  local wave = {}
  for i = 0, 31 do wave[i] = (i % 16) / 15 end
  local lfsr, acc, ph = 0x7fff, 0, 0
  local t0 = now()
  for _ = 1, n do
    ph = ph + 0.0371
    if ph >= 32 then ph = ph - 32 end
    local fb = band(bxor(lfsr, rshift(lfsr, 1)), 1)
    lfsr = bor(rshift(lfsr, 1), lshift(fb, 14))
    acc = acc + wave[floor(ph)] * 0.25 + band(lfsr, 1) * 0.1
  end
  return (now() - t0) * 1000, acc
end

local function benchTables(n)
  local t0 = now()
  local keep = {}
  for i = 1, n do
    keep[(i % 1000) + 1] = { x = i, y = i * 2, name = "t" }
  end
  collectgarbage("collect")
  return (now() - t0) * 1000
end

local function benchStrings(n)
  local t0 = now()
  local s
  for i = 1, n do
    s = ("%s Lv%d %d/%d"):format("PIKACHU", i % 100, i % 300, 300)
  end
  return (now() - t0) * 1000, s
end

-- The music path's real per-buffer cost outside synthesis: writing 8192
-- stereo samples through SoundData:setSample, as ChipSynth.soundData does.
local function benchSoundData()
  local sd = love.sound.newSoundData(8192, 44100, 16, 2)
  local t0 = now()
  local v = 0
  for i = 0, 8191 do
    v = ((i % 100) < 50) and 0.2 or -0.2
    sd:setSample(i, 1, v)
    sd:setSample(i, 2, v)
  end
  local ms = (now() - t0) * 1000
  return ms, sd
end

local function cpuInfo()
  section("CPU (lower is faster)")
  local synthMs = benchSynth(2000000)
  add("synth loop 2M", synthMs and ("%.0f ms"):format(synthMs) or "skipped (no bit)")
  add("table churn 300k", ("%.0f ms"):format(benchTables(300000)))
  add("string.format 100k", ("%.0f ms"):format(benchStrings(100000)))
  local okSd, sdMs, sd = pcall(benchSoundData)
  if okSd then
    local bufferMs = 8192 / 44100 * 1000
    add("setSample 8192x2", ("%.1f ms (buffer lasts %.0f ms)"):format(sdMs, bufferMs))
    try("QueueableSource", function()
      local q = love.audio.newQueueableSource(44100, 16, 2, 32)
      q:queue(sd)
      q:setVolume(0.3)
      q:play()
      return "ok, free buffers " .. q:getFreeBufferCount()
    end)
  else
    add("SoundData", "ERROR " .. tostring(sdMs))
  end
  add("gc KB", ("%.0f"):format(collectgarbage("count")))
end

-- ---------------------------------------------------------------------------
-- GPU: a Game Boy screen's worth of tiles into a 160x144 canvas, scaled 3x
-- ---------------------------------------------------------------------------

local function setupDraw()
  local img = love.image.newImageData(128, 128)
  img:mapPixel(function(x, y)
    local c = ((math.floor(x / 8) + math.floor(y / 8)) % 4) / 3
    if (x + y) % 3 == 0 then c = 1 - c end
    return c, c, c, 1
  end)
  tileset = love.graphics.newImage(img)
  tileset:setFilter("nearest", "nearest")
  quads = {}
  for i = 0, 255 do
    quads[i] = love.graphics.newQuad((i % 16) * 8, math.floor(i / 16) * 8, 8, 8, 128, 128)
  end
  batch = love.graphics.newSpriteBatch(tileset, 400, "stream")
  canvas = love.graphics.newCanvas(160, 144)
  canvas:setFilter("nearest", "nearest")
  local ok, sh = pcall(love.graphics.newShader, [[
    extern vec4 pal0; extern vec4 pal1; extern vec4 pal2; extern vec4 pal3;
    vec4 effect(vec4 color, Image tex, vec2 uv, vec2 sc) {
      float l = Texel(tex, uv).r;
      vec4 c = l < 0.17 ? pal0 : (l < 0.5 ? pal1 : (l < 0.83 ? pal2 : pal3));
      return c * color;
    }
  ]])
  if ok then
    palShader = sh
    sh:send("pal0", { 0.06, 0.22, 0.06, 1 })
    sh:send("pal1", { 0.19, 0.38, 0.19, 1 })
    sh:send("pal2", { 0.55, 0.67, 0.06, 1 })
    sh:send("pal3", { 0.61, 0.74, 0.06, 1 })
  end
end

local function drawStress(t, useBatch)
  love.graphics.setCanvas(canvas)
  love.graphics.clear(0, 0, 0, 1)
  local scroll = math.floor(t * 30) % 8
  if useBatch then
    batch:clear()
    for ty = 0, 18 do
      for tx = 0, 20 do
        batch:add(quads[(tx * 7 + ty * 3 + math.floor(t * 4)) % 256], tx * 8 - scroll, ty * 8 - scroll)
      end
    end
    love.graphics.draw(batch)
  else
    for ty = 0, 18 do
      for tx = 0, 20 do
        love.graphics.draw(tileset, quads[(tx * 7 + ty * 3 + math.floor(t * 4)) % 256], tx * 8 - scroll, ty * 8 - scroll)
      end
    end
  end
  -- 40 OAM sprites on top
  for i = 0, 39 do
    love.graphics.draw(tileset, quads[i], (i * 17 + t * 40) % 160, (i * 11) % 144)
  end
  love.graphics.setCanvas()
  if palShader then love.graphics.setShader(palShader) end
  love.graphics.draw(canvas, 480, 56, 0, 3, 3)
  love.graphics.setShader()
end

-- ---------------------------------------------------------------------------
-- Output
-- ---------------------------------------------------------------------------

local function writeResults()
  local text = table.concat(results, "\n") .. "\n"
  local targets = {}
  if love.filesystem.write("probe.txt", text) then
    targets[#targets + 1] = love.filesystem.getSaveDirectory() .. "/probe.txt"
  end
  local f = io.open("ux0:data/gen1recomp-probe.txt", "w")
  if f then
    f:write(text)
    f:close()
    targets[#targets + 1] = "ux0:data/gen1recomp-probe.txt"
  end
  writeTarget = #targets > 0 and table.concat(targets, " and ") or "WRITE FAILED"
  written = true
  -- desktop baseline runs: PROBE_AUTOQUIT=1 lovec build/game
  if os.getenv("PROBE_AUTOQUIT") then love.event.quit() end
end

-- ---------------------------------------------------------------------------
-- LÖVE callbacks
-- ---------------------------------------------------------------------------

function love.load()
  font = love.graphics.newFont(13)
  smallFont = love.graphics.newFont(11)
  staticInfo()
  startThread()
end

function love.update(dt)
  if thread and threadChannel then
    local msg = threadChannel:pop()
    if msg then
      section("Thread")
      add("worker", ("%s (%.0f ms)"):format(msg, (now() - threadStart) * 1000))
      thread, threadChannel = nil, nil
    elseif thread:getError() then
      section("Thread")
      add("worker", "ERROR " .. thread:getError())
      thread, threadChannel = nil, nil
    end
  end

  if phase == "static" then
    phase = "heavy" -- one frame on screen before the blocking work
  elseif phase == "heavy" then
    shaderInfo()
    bytecodeInfo()
    cpuInfo()
    setupDraw()
    phase, phaseStart = "draw-single", now()
    drawStats = { frames = 0, dtSum = 0, worst = 0, cpuSum = 0 }
  elseif phase == "draw-single" or phase == "draw-batch" then
    -- the first frames absorb the blocking benchmark and texture uploads
    drawStats.warmup = (drawStats.warmup or 0) + 1
    if drawStats.warmup > 5 then
      drawStats.frames = drawStats.frames + 1
      drawStats.dtSum = drawStats.dtSum + dt
      if dt > drawStats.worst then drawStats.worst = dt end
    end
    if now() - phaseStart > 3 then
      if phase == "draw-single" then
        section("GPU (60 fps = 16.7 ms)")
      end
      local label = phase == "draw-single" and "tiles, 420 draws" or "tiles, spritebatch"
      add(label, ("avg %.1f ms/frame, worst %.1f, draw cpu %.1f ms"):format(
        drawStats.dtSum / drawStats.frames * 1000, drawStats.worst * 1000,
        drawStats.cpuSum / drawStats.frames * 1000))
      if phase == "draw-single" then
        phase, phaseStart = "draw-batch", now()
        drawStats = { frames = 0, dtSum = 0, worst = 0, cpuSum = 0 }
      else
        phase = "done"
      end
    end
  elseif phase == "done" and not written and not thread then
    writeResults()
  end
end

local function drawColumns(list, x0, y0, colWidth, lineH, maxRows)
  local col, row = 0, 0
  for _, line in ipairs(list) do
    if line:sub(1, 3) == "== " then
      love.graphics.setColor(1, 0.85, 0.3)
    elseif line:find("ERROR") or line:find("FAIL") or line:find("MISSING") then
      love.graphics.setColor(1, 0.4, 0.4)
    else
      love.graphics.setColor(0.9, 0.9, 0.9)
    end
    love.graphics.print(line, x0 + col * colWidth, y0 + row * lineH)
    row = row + 1
    if row >= maxRows then row, col = 0, col + 1 end
  end
  love.graphics.setColor(1, 1, 1)
end

function love.draw()
  local t0 = now()
  if phase == "draw-single" or phase == "draw-batch" then
    drawStress(now() - phaseStart, phase == "draw-batch")
    if (drawStats.warmup or 0) > 5 then
      drawStats.cpuSum = drawStats.cpuSum + (now() - t0)
    end
  end

  love.graphics.setFont(smallFont)
  local lineH = 13
  local maxRows = math.floor((544 - 40) / lineH)
  local width = (phase == "draw-single" or phase == "draw-batch") and 470 or 952
  love.graphics.setScissor(0, 0, width, 544)
  drawColumns(results, 4, 4, 318, lineH, maxRows)
  love.graphics.setScissor()

  love.graphics.setFont(font)
  local status
  if phase == "static" or phase == "heavy" then
    status = "Running shader + CPU tests (the screen may freeze a few seconds)..."
  elseif phase ~= "done" then
    status = "GPU test: " .. phase
  elseif written then
    status = "Done. Saved to " .. writeTarget .. ".  Press START to quit."
  else
    status = "Waiting for thread result..."
  end
  if #inputLog > 0 then status = status .. "   input: " .. table.concat(inputLog, " ") end
  love.graphics.setColor(0.3, 0.9, 1)
  love.graphics.print(status, 4, 544 - 20)
  love.graphics.setColor(1, 1, 1)
end

local function logInput(name)
  table.insert(inputLog, 1, name)
  if #inputLog > 6 then inputLog[#inputLog] = nil end
end

function love.gamepadpressed(_, button)
  logInput("pad:" .. button)
  if button == "start" then love.event.quit() end
end

function love.keypressed(key)
  logInput("key:" .. key)
  if key == "escape" then love.event.quit() end
end

function love.touchpressed(_, x, y)
  logInput(("touch:%d,%d"):format(x, y))
end
